### ISSUE TITLE
"Manage your Email Preferences" page is throwing an error

### ISSUE THREAD

**Issue by LuminitaB** [mozmeao/basket#1023]
**FxA version:**
1.256.3

**Prerequisites:**
Have a Fxa account;

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and login using an existing account;
2. Click on the "Email communications" option displayed in the navigation menu;
3. Click on "Sign in" button;

**Expected result:**
The user is taken to the Manage your Email Preferences page and the options are successfully displayed;

**Actual result:**
The user is taken to the Manage your Email Preferences page but an error is displayed;

Notes:
The issue reproduces intermittently and/or for specific accounts. I was able to constantly reproduce with: lburuian+fxaprod@mozilla.com | Test1234!

**Another scenario:**
1. For an account that works, make some selections for email preferences and save
2. Go back to preferences and select to remove from all subscriptions and save
3. Go back to check that all options have been deselected
I get the same error!

![image](https://user-images.githubusercontent.com/52028275/233591005-3455598b-6b05-427e-9b7a-298f4241a0f1.png)

**Comment by alexgibson** [comment]
Possible related to https://github.com/mozmeao/basket/issues/928

**Comment by pmac** [comment]
In my testing with the `another scenario` method I don't see what you're seeing Alex. I see all 200 responses from basket, but I do see that the user data does not come back with a `newsletters` key. Perhaps this is a change in basket.

**Comment by pmac** [comment]
We just landed a fix that has fixed the issue Alex and I were able to reproduce on staging. I'll get it to prod shortly.

**Comment by LuminitaB** [comment]
Verified as fixed on Train 1.257.1
We did not encounter the error anymore.
Thank you.
