### ISSUE TITLE
Add support for new fields for incoming data from MoFo Donations

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#103]
https://docs.google.com/document/d/1o7acbXWxQEdyBlz_48ukGf0RNV7q0LhQLSKB3boxN2s/edit?ts=5bbe6bde

**Comment by pmac** [comment]
@cadecairos this is now deployed to dev, so we can test some messages on the staging queue and it should update the ADVO SFDC sandbox.

**Comment by cadecairos** [comment]
Awesome! Just a heads up, until I ship one last fix to staging, non-USD microtransactions will return `NaN` for fees, converted, and net.

**Comment by pmac** [comment]
@cadecairos hmm... so I'm guessing that means that I should check the value and only add it to SFDC if it's a positive float? I'm guessing a `NaN` would translate to a Python `None`. I can test that though. Might need a followup for that to work.

**Comment by pmac** [comment]
Actually it looks like `NaN` isn't valid in a JSON string. So will you just be omitting those keys from the data, or putting in a `0` value? I already handle them just not being in the data. They're all optional for now. I can easily handle either `0` or `-1` or something as well if you want.

**Comment by cadecairos** [comment]
Once the fix lands, the keys and values that currently come in as `NaN` will be omitted from the message to basket, so there shouldn't be any need for special casing on Basket.

**Comment by cadecairos** [comment]
OK the fix should be live on staging now.

**Comment by pmac** [comment]
Nice! Thanks! We should be good to go for some testing then.
