### ISSUE TITLE
Not working:   Get more fox in your inbox... Button redirect to json

### ISSUE THREAD

**Issue by wellington1993** [mozmeao/basket#118]
Browser new page alert for subscribe not working. Redirect to JSON : .."/subscription.json"

**Comment by pmac** [comment]
Do you have more details on what exactly isn't working? A screenshot or URL or something like that would  be very helpful. Thanks for reporting!

**Comment by wellington1993** [comment]
@pmac I can reproduce but when the form is displayed, and that form not displayed now.

The subscription form from the new page (dynamic page ) redirects to the subscription server but with the end with subscription.json.

I'm curious about that because "GET" is not common to send data like email to the server and because the user get a blank page instead of a subscription.

If the dialog appears again I will do some screenshots for you.
Thanks!

**Comment by pmac** [comment]
It should definitely be a `POST` request, not `GET`, so you're right that something is very wrong. Thanks!

**Comment by robhudson** [comment]
This is 6 years old. I'll close. Re-open if this still persists.
