### ISSUE TITLE
Duplicate Contact Record in SFDC via Basket

### ISSUE THREAD

**Issue by stephaniemcv** [mozmeao/basket#125]
Contact Record - 0030B00002Ha9lzQAB and 0030B00002Ha9m4QAB

These contact records have the same email address, created by (basket), created date/time, source url, and newsletter subscriptions.

Where they differ is Contact Record Type (Advocacy vs Subscribers), Name (Full Name vs "_") and Newsletter Language (DE vs EN).

Only 0030B00002Ha9lzQAB is associated with the Petition Campaign though both records indicate that is their source. Not an urgent matter but caught my attention since the source is a petition.

**Comment by robhudson** [comment]
With Salesforce no longer in used, I'm closing this.
