### ISSUE TITLE
Docs reference nonexistent file

### ISSUE THREAD

**Issue by heatherbooker** [mozmeao/basket#13]
The [docs](https://basket.readthedocs.io/install.html) instruct one to run

```bash
pip install -r requirements/default.txt
```

but this file doesn't seem to exist! What should it be replaced with?

```bash
#1
pip install -r requirements.txt
#2
pip install -r requirements/base.txt
#3
pip install -r <something_else>
```

Thanks!

**Comment by pmac** [comment]
doh! thanks for finding these. clearly I failed to update the docs when changing things for new deployment. For development you should use: `pip install -r requirements/dev.txt`.

**Comment by pmac** [comment]
I hope to have a better setup soon that uses Docker, so you shouldn't need to worry with this after that. But for now the above should work. I'll see about fixing the docs as well. I'm sure there are other problems :(

**Comment by heatherbooker** [comment]
Haha! Sounds good. I'm also not sure how to run the server - I tried `bin/run-dev.sh` but it complained there was no DATABASE_URL, so I tried exporting:

mysql://root@db/basket --> "Could not connect to mysql://root@db/basket"

sqlite:///basket.db --> "Could not guess port for sqlite"

I'd love to know how to do that too :D let me know if this isn't the place for this!

**Comment by pmac** [comment]
This is fine. Apologies for the trouble. I normally just run it as a typical Django project.

```bash
$ ./manage.py runserver
```

The `run-dev.sh` script is mostly for docker.

Another good place to hash these things out is in the `#basket` channel on irc.mozilla.org. I'm `pmac` there as well. But here is also good because others may well have these problems.
