### ISSUE TITLE
Store Commonvoice Contact Data

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#135]
Take in Commonvoice data (either via HTTP API or Queue) and store it in SFMC. We'll discuss the details of the data to be exchanged and the method here.

/cc @gregoor

**Comment by Gregoor** [comment]
So there's 3 Re-Engagement emails:

1) First contribution
2) Close to 3 day streak
3) "We miss your voice" - inactive for a certain interval

My understanding from the meeting is that we wouldn't send "triggers" when to send out those mails but rather constantly sync fields that would allow you to set rules in the Salesforce Backend?

Under that assumption, the fields should be sth like:

1) `first_contribution_date: Date`
2) `two_day_streak_going: boolean`
3) `last_active_date: Date`

Does that make sense?

**Comment by Gregoor** [comment]
How does that look @pmac ?

**Comment by pmac** [comment]
that looks fine to me @Gregoor. Do you have thoughts @LaurenNiolet ?

**Comment by pmac** [comment]
@Gregoor in what format would you like to send the date? ISO 8601 or Unix timestamp or other? Doesn't matter much to me really.

**Comment by Gregoor** [comment]
I like ISO-8601, because I can also visually parse it. So if it's all the same to you... 🙂

**Comment by pmac** [comment]
Works for me 👍

**Comment by Gregoor** [comment]
I realized I forgot to describe what we need for goal emails here. So there's another email type for which the following fields would be relevant:
`goal_type: 'daily' | 'weekly'`
`goal_mode: 'speak' | 'listen' | 'both'`
`goal_diff: number`

What's still not quite clear to me is how you'd define the rules when to send those mails out. In my mind it seems simpler for us to send some sort of trigger to your system that a specific mail with specific data should be send out. Is that a heavier lift from your side?

**Comment by pmac** [comment]
Those are questions for @LaurenNiolet. I'll ping her on slack.

**Comment by Gregoor** [comment]
@pmac sth I've been wondering about: we would be able to have different signups for newsletter and goals right? But both would still be managed through mozilla.org, right?

**Comment by pmac** [comment]
What do you mean by "managed"? We'd still have newsletter signups and the users will be able to manage that subscription through the email preferences center on www.mozilla.org, but the other data is just a function of being signed up for he service and I don't think would have any entries on the email preferences center.

**Comment by Gregoor** [comment]
So for "goals" our thinking was that people could be subscribed to those, without necessarily being subscribed to the newsletter. Maybe that's taken for granted, just want to be sure that this would work and these two are indeed separate?

**Comment by pmac** [comment]
Yes. That is how it should work. These two things will be fully separate, though we'll be able to know if a user is also subscribed to the newsletter.

**Comment by Gregoor** [comment]
okay, great. Good to hear, thanks! :)

**Comment by LaurenNiolet** [comment]
Hi friends. I'm just back from PTO. Are there any outstanding questions for me?

**Comment by Gregoor** [comment]
Heya, welcome back! 🎉 I guess the only question I have is when I can start implementing it? 🙃

**Comment by pmac** [comment]
I belive @Gregoor's comment from above is still an open question:

https://github.com/mozmeao/basket/issues/135#issuecomment-470673792

**Comment by LaurenNiolet** [comment]
> 
> 
> I realized I forgot to describe what we need for goal emails here. So there's another email type for which the following fields would be relevant:
> `goal_type: 'daily' | 'weekly'`
> `goal_mode: 'speak' | 'listen' | 'both'`
> `goal_diff: number`
> 
> What's still not quite clear to me is how you'd define the rules when to send those mails out. In my mind it seems simpler for us to send some sort of trigger to your system that a specific mail with specific data should be send out. Is that a heavier lift from your side?

If these are going to Marketing Cloud and not Salescloud, we'd have to set up a query to "listen" for the updated fields to match our send criteria. 

I think that's much easier than sending the triggers via API or some other method. 

If the data is going to Salescloud, then it's easy mode since we can set up rules to trigger the right email under the right circumstances. 

Is anyone from LifeCycle Marketing involved in this project?

**Comment by Gregoor** [comment]
Oh sorry, I missed the response. That's good to hear, thanks! I think I had some misunderstanding how it'd work before and now I do have some changes we'd have to make to the fields, so I hope it's indeed easy mode to change (if they're already there).

I'd wanna change `goal_type` to `days_interval: null | 1 | 7`, which is closer to how we save it. Also I think instead of `goal_diff` we'd need `created_at: Datetime` and `goal_reached_at: Datetime`. From Common Voice we'd then update `goal_reached_at` whenever it is reached.
On your side there would be rules to send a goal reminder email if the current interval is half over (which should be inferrable from `created_at` and `days_interval`) and if goal_reached_at isn't in the current interval.

Does that make sense? I guess we can talk about it later in our meeting.

**Comment by pmac** [comment]
@Gregoor Just making sure here. We've decided on HTTPS transfer for data, meaning that I will be adding a new API endpoint to basket (e.g. /news/common-voice/) to which your service will POST data. And the data to be posted will be the above? In what format would you prefer the data exchange? Form encoded like a web submission, or JSON, or other? I'm happy with anything. Also we need to work out exactly the parameter names and possible values basket should expect.

**Comment by Gregoor** [comment]
Great! Whatever's most consistent with what you're already doing with that API works for me :)

For goals we need:
`days_interval: null | 1 | 7`
`created_at: Datetime`
`goal_reached_at: Datetime`

For the other emails we need:
`first_contribution_date: Datetime`
`two_day_streak_going: boolean`
`last_active_date: Datetime`

**Comment by pmac** [comment]
Based on the email from yesterday it looks like we'll need to receive the following fields from CV to a new basket API endpoint:

```
email: String
days_interval: null | 1 | 7
created_at: Datetime
goal_reached_at: Datetime
first_contribution_date: Datetime
```

When basket receives this, should it also make sure the user is subscribed to a certain newsletter, or will you be sending a subscription call separately? I believe the former, but I wanted to be sure.

**Comment by Gregoor** [comment]
looks good :+1:

I'd continue using the other endpoint for subscription if that's alright.

**Comment by pmac** [comment]
That's fine. Should this endpoint double check though and add that subscription if it's not present? If so which newsletter is it?

**Comment by pmac** [comment]
Oh, and which datetime format are you planning to send? Unix timestamp or ISO 8601 I think should work fine.

**Comment by Gregoor** [comment]
I'd make sure to only send it for users who have a basket tokens. And subscription status wise we went the route of not managing it and linking users to m.o/newsletters

**Comment by brynneh** [comment]
Hi Pmac -

Anyone coming through should be a "Sub_Common_Voice__c" (slug:
common-voice) subscriber.

Brynne

**Comment by pmac** [comment]
@Gregoor and as far as POST data format it'd be easiest for me if it were form-encoded like a normal HTML form submission. I'll also need to get you an API key for this so that these submissions can be authenticated and not just anyone can add data and game the system.

**Comment by Gregoor** [comment]
Works for me as well 👍 We do already have an API key for basket, do we need a new one? Could we btw also have ones for staging?

**Comment by pmac** [comment]
oh. great. I forgot about that. One is fine and will work for this as well.
