### ISSUE TITLE
[Android] The user gets an error when checking the "Remove me from all the subscriptions on this page" checkbox

### ISSUE THREAD

**Issue by LuminitaB** [mozmeao/basket#1424]
### FxA version:

- 1.287.3

### Prerequisites:

- Have a Mozilla account;

### Steps to reproduce

1. Navigate to https://accounts.firefox.com/ and login using an existing account;
2. Click on the "Email communications" option displayed in the navigation menu;
3. Click on "Sign in" button;
4. Check the "Remove me from all the subscriptions on this page" checkbox displayed at the bottom of the page and click the Save Preferences button;

### Expected result

The user is taken to the "You’ve been unsubscribed." page

### Actual result

The user gets an error on the page but is still unsubscribed.
Refreshing the page shows no options checked

![image](https://github.com/mozmeao/basket/assets/52028275/eadee2af-2753-4b0d-89e0-ebe0b8ad789c)

### Environment
Production

### What browser and operating system are you using?
Firefox Release for Android,  v125.3.0. / Android 9

**Comment by robhudson** [comment]
Moved to https://github.com/mozilla/bedrock/issues/14757
