### ISSUE TITLE
contact sync for extension devs

### ISSUE THREAD

**Issue by metadave** [mozmeao/basket#148]
* [Project Brief](https://docs.google.com/document/d/1PPy8H_foBrgY-Ls3rQANham65N54-SkzDfPrXmvNq1s/edit#heading=h.4ffvr8b36hfh)
* [AMO Fields](https://docs.google.com/spreadsheets/d/1WMsA9ukyLVlyiNtveVijdsbfdcDMkkhsGZ56NrGjMQQ/edit?pli=1#gid=0)
* [SFDC Fields](https://docs.google.com/spreadsheets/d/1gHQOoJd5XaUCBNAU58Nf6HHxsZOzYg6DbKow6RoVUqk/edit?pli=1#gid=0)
* [AMO Sync Spec](https://gist.github.com/diox/aa83b4ce9cb23c906cb87a064857e133)

**Comment by pmac** [comment]
This merged but is in QA now.

**Comment by pmac** [comment]
I believe we can call this one done. All changes for all known issues are merged and deployed.
