### ISSUE TITLE
adding a new event type to basket

### ISSUE THREAD

**Issue by Pomax** [mozmeao/basket#152]
For the foundation website's newsletter(s) signup functionality, we'd like to send signup events on a new event type. We're currently using `crm_petition_data` for mofo petitions, but we'd like to also have a `newsletter_signup_data` event type for dealing with (comma-separated) newsletter(s) that users can register for.

**Comment by Pomax** [comment]
code that was already in place: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L156-L166

new (currently inactive) code that will use the new event type: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L93-L103

**Comment by pmac** [comment]
That's good enough for me. Thanks!

**Comment by pmac** [comment]
@Pomax there are some other fields that we can accept and would be nice if your system knows them. 

The full list is in the [basket docs](https://basket.readthedocs.io/newsletter_api.html#news-subscribe), but the important ones are `lang` and `format`. `country` also comes in handy if you happen to gather that info, but isn't required at all.

**Comment by Pomax** [comment]
Ah, good to know. 

Unfortunately, for newsletters all we have right now is email address (users are not asked to supply any additional information at the moment, so if we want to supply the additional information we will first need to figure out how to update the site component design to allow for gathering that data)

**Comment by pmac** [comment]
@Pomax it would be best then to send the language of the page (or just hard-code `en`) or to capture the user's `accept-language` header value and send that. If no language is sent then no language is recorded and people may not receive a newsletter at all since they usually use language to segment sends.

**Comment by pmac** [comment]
HTML is the default for `format`, so that's okay, and I don't think `country` is used much outside of advocacy things that are country specific.

**Comment by pmac** [comment]
you can see the form at https://www.mozilla.org/en-US/newsletter/ for the standard info we request at signup.

**Comment by Pomax** [comment]
gotcha, filed https://github.com/mozilla/foundation.mozilla.org/pull/2992 to make sure the lang and format fields will have a value, pending "real" form redesign
