### ISSUE TITLE
Include FxA Tips subscription info with user data

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#161]
Include the FxA tips subscirption status of an email address with requests to `lookup-user`. This data is in data extensions in SFMC. The user must be in the FxA account holders extension, and not in the FxA account opt-out extension. The data returned can have 3 states for this. 

1. Nothing returned for `fxa-tips` means that the user has no record of having an FxA.
2. `True` means the user is an FxA holder, but has no opt-out.
3. `False` means the user is an FxA holder, but has an opt-out.

**Comment by ldwright** [comment]
Please coordinate with Lauren Niolet on the plan surrounding FxA Tips.

_Based on the current plan to my knowledge, we are sunsetting the existing Firefox Accounts Tips subscription, and there will not be any sort of new FxA Tips subscription stood up. See doc below._

https://docs.google.com/spreadsheets/d/1CdsuwXBhXhJ9LBMthRMDx9ATEGWDiKXlZoPFWLjjKzI/edit#gid=0

**Comment by pmac** [comment]
Right. I was trying to refer to the FxA account holders emails that currently come only from SFMC. That's what this issue is about. The current newsletter should be unaffected by this work.

**Comment by pmac** [comment]
Updates: We will not need to indicate whether the user has opted out of these emails because the opt-out mechanism is being removed and opt-out will now only be possible via FxA deletion. So this will only need to return something like `'fxa-user': True` or `False`.

**Comment by pmac** [comment]
We should also make inclusion of that data optional via a query param to these requests. We'll sometimes be able to know if they're an FxA user via other means, so there will be no need to take the time to look them up in SFMC in those cases.
