### ISSUE TITLE
Add a section field to newsletters data

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#162]
Add a choice field (choices TBD, but will be things like "firefox" and "mozilla") to the Newsletter model and have that data returned with the newsletters data for use by bedrock. This is part of a request for bedrock to organize newsletters into groups.

**Comment by ldwright** [comment]
This issue should no longer be relevant based on the current plan found here:

- https://docs.google.com/presentation/d/1lYEG-a30ram5L6pubUXMNyB7A0CNNIbLvFEK0HKBnh0/edit#slide=id.p
- https://docs.google.com/spreadsheets/d/1CdsuwXBhXhJ9LBMthRMDx9ATEGWDiKXlZoPFWLjjKzI/edit#gid=0

**Comment by pmac** [comment]
Thanks for the update! Closing for now.
