### ISSUE TITLE
Additional Common Voice fields (2 day streak & Last Active date)

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#164]
There are 2 new fields that we need ported over from Common Voice into SFDC. The fields are: 

2 day streak / boolean (cv_two_day_streak__c)
Common Voice Last Active Date (date) (cv_last_active_dt__c)

Please work with Desiree and Gregor w/ the Common Voice team to get these data values tested in the ADVO SFDC Sandbox, then moved to Production.

**Comment by desiree-mofo** [comment]
@pmac  - fields added to the ADVO sandbox this morning (FYI)

**Comment by pmac** [comment]
Just merged the changes to basket, and so they should be live on basket-dev shortly.
