### ISSUE TITLE
New REST endpoint for Subscription processor to CRM

### ISSUE THREAD

**Issue by spiropulo** [mozmeao/basket#166]
We will be posting webhook events from payment provider to subscription processor to CRM. Here is a sample request:

```json
{
    "type" : "charge.succeeded",
    "payload" : { "id" : "someid", "someotherfield" : "someothervalue"}
}
```

The payload is generic, the Basket program will have to parse based on the type. The definition for each type is currently being worked on. We are assuming this should affect the signature of the REST endpoint we need from Basket.

**Comment by pmac** [comment]
Is work currently happening to define which `type`s and the schema of each `payload` type we should expect? As soon as those as well as the corresponding Salesforce field names and content types are defined work can begin. I'm a bit bogged down with Trailhead things at the moment, but I do get some time while waiting for approvals and things, so I could get going on this as soon as details are provided. 

/cc @desiree-mofo

**Comment by desiree-mofo** [comment]
The specs for the payloads from Stripe and what fields they map to in Salesforce are included in this document: [https://docs.google.com/document/d/1xlrPE_-CMGsj7QTHl2XsOVkQtBDLjgz0AHwUwM1hP00/edit#
