### ISSUE TITLE
Add new endpoint for FxA to lookup users and redirect to preference center

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#167]
We're still working out whether this will need to accept only an FxA ID, or also another random token, but it will need to do the following:

1. Look up the user using the token provided in SFMC FxA table
2. Using the email returned, look up the user in SFDC
    * If no SFDC record found for user, create one, and redirect to the email pref center on bedrock using the new token
    * If SFDC record is found, use the token in that record to redirect to the email pref center on bedrock
3. Include a query param (e.g. `?fxa=1`) on the links to the email pref center so that a new lookup of the user in SFDC is not required. The request for user data in that case should not ask for FxA status.

**Comment by pmac** [comment]
@shane-tomlinson yo. Is there something I can do to get started on this bit or is there more for you to do on your side? I know the desire is simply to have a good URL we can put in emails or on websites that will result in a user seeing their email preferences page. Whether that URL starts at basket or FxA doesn't matter to me.

**Comment by shane-tomlinson** [comment]
> yo. Is there something I can do to get started on this bit or is there more for you to do on your side? 

I'll comment more tomorrow. The TL;DR is I think the basic plan we came up with the other day is still sound, with some slight modifications. To avoid being the blocker, I'm trying to rope either @dannycoates or @vbudhram into taking over (and of course need to talk to them about it!)

**Comment by shane-tomlinson** [comment]
@vbudhram is going to take over this work. Copying some context from the email:

> I think there is a path forward that provides the security we want with a reasonable UI. If we add support for [`prompt=none`](https://github.com/mozilla/fxa/issues/640), we could have users bounce off of an endpoint on Basket that sets up the OAuth state token and binds it to the session, then redirects to FxA with ?prompt=none. If the user is signed into FxA, we redirect back to Basket with OAuth credentials without requiring user interaction. I have put added a new diagram below with this flow. There are a lot of redirects, but this approach could work as a generic solution to other problems we have too (securing the payments page).
>
> FxA->Basket (setup OAuth CSRF protection)->FxA w/ prompt=none->Basket w/ OAuth credentials.
>
> There are some details that are being glossed over, but I really think it could work. 


![basket-from-communication-prefs-real-state-token](https://user-images.githubusercontent.com/848085/57950846-4fe62100-78e0-11e9-9549-44fb7ed971b5.png)

**Comment by pmac** [comment]
Note: This flow should add a default subscription to `firefox-accounts-journey` for any new CRM records created.

**Comment by shane-tomlinson** [comment]
> Note: This flow should add a default subscription to firefox-accounts-journey for any new CRM records created.

Would we add `firefox-accounts-journey` on our side, or can you handle that automatically on your side when the `verified` event arrives?

**Comment by pmac** [comment]
> Would we add `firefox-accounts-journey` on our side, or can you handle that automatically on your side when the `verified` event arrives?

I can handle it. It's going to be default `True` for everyone created during an FxA flow, so basket can do that both from the verified events and when a new CRM record is created from a link to the pref center.

**Comment by pmac** [comment]
#185 should not have closed this.
