### ISSUE TITLE
None value throwing errors in sfdc.py/to_vendor

### ISSUE THREAD

**Issue by jpetto** [mozmeao/basket#195]
Appears to be similar to #193. Changes to MoFo are impacting collecting subscriptions.

Specific error is [this line in sfdc.py in the `to_vendor` method](https://github.com/mozmeao/basket/blob/prod/basket/news/backends/sfdc.py#L165):

`if field in contact and len(contact[field]) > length:`

Error thrown is: `TypeError: object of type 'NoneType' has no len()`

Sentry shows `FirstName` has a value of `None`.

Error report is [here](https://sentry.prod.mozaws.net/operations/basket-prod/issues/5947191/).

**Comment by alanmoo** [comment]
Did the items I put in this morning not take?

**Comment by jpetto** [comment]
After a quick look the data for these errors doesn't appear to match that from yesterday.
