### ISSUE TITLE
SubHub / Salesforce - Verify plan name is handled by basket

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#202]
The Subhub team is ready to pass through the Plan name from Subhub (and/or Stripe) to Salesforce. The field exists in Salesforce (Opportunity.Service_Plan__c) and I am confirming the event + field name in Stripe. Please verify that basket is ready to pass this value through to Salesforce. 

Field mappings and documentation here: https://docs.google.com/document/d/1xlrPE_-CMGsj7QTHl2XsOVkQtBDLjgz0AHwUwM1hP00/edit#

**Comment by jpetto** [comment]
Acting on the assumption that the `description` field coming in from SubHub, which maps to `Opportunity.Service_Plan__c`, will only be present in the data for the `invoice.finalized` event and **not** the `payment_intent.succeeded` event:

We will pass the `description` value to the `Service_Plan__c` Salesforce field only for the `invoice.finalized` event.

Does this sound correct?

**Comment by jpetto** [comment]
plan name is now flowing from subhub to basket to salesforce.
