### ISSUE TITLE
Populate SFMC Data Extension with EmailAddress for Credit Card Expiring Notifcation

### ISSUE THREAD

**Issue by mozbrandon** [mozmeao/basket#204]
There is a Stripe event that occurs 30 days before a customer's credit card on file is due to expire. 

The email address of the customer whose card is expiring needs to be captured in an SFMC Data Extension.

Data Extension: customer_card_expiring
Location: Shared Items > Shared Data Extensions > Subscription_Services 
Schema: name(EmailAddress), fieldtype(EmailAddress).

_Relates internally to SS-213_

**Comment by pmac** [comment]
We ended up going with a triggered send to handle this. See #264.
