### ISSUE TITLE
check valid data in subhub view

### ISSUE THREAD

**Issue by jpetto** [mozmeao/basket#209]
As we don't have a sandbox for SFMC, and just for general improvements to end to end testing, we should make sure the necessary data is present in the POST JSON payload prior to returning a 200 and offloading to the task worker.

Currently, we only check that a POST JSON payload is present.

**Comment by jpetto** [comment]
cc @pmac

**Comment by pmac** [comment]
We're going to call this `wontfix` since it's working well now and SubHub's plan for the future is to directly integrate with Salesforce.
