### ISSUE TITLE
Reduce the TTL of the OAuth access token for FxA

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#256]
See https://github.com/mozilla/fxa/issues/1810

**Comment by pmac** [comment]
@shane-tomlinson I'm looking at my code and I'm not seeing an opportunity to set a TTL for anything I'm doing. Is it an optional parameter for the authorization URL I send them to, or does it need to happen when exchanging the code I get when the user is redirected to me for the access token?

https://github.com/mozmeao/basket/blob/76773ce909f76a2a2bed5e8f4445c2f401e5ac73/basket/news/views.py#L199

**Comment by pmac** [comment]
If it's the latter we may need to add the option to the PyFxA library.

**Comment by shane-tomlinson** [comment]
> If it's the latter we may need to add the option to the PyFxA library.

[It is the latter](https://github.com/mozilla/fxa/blob/6f64b72608db4095cc903026198e93a40549ea84/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js#L102). Opened a [PyFxA PR](https://github.com/mozilla/PyFxA/pull/75) to help out.

**Comment by rfk** [comment]
@pmac what python version do you need for this, by the way? I note that CI is currently busted for PyFxA because its dependencies have been dropping support for python2 (as well they should) but not sure how to proceed with fixing that...

**Comment by rfk** [comment]
Thanks @shane-tomlinson, published in [PyFxA v0.7.3](https://pypi.org/project/PyFxA/0.7.3/).

**Comment by shane-tomlinson** [comment]
> Thanks @shane-tomlinson, published in PyFxA v0.7.3.

Perfect. Thanks.

**Comment by pmac** [comment]
Thanks y'all! @rfk basket is running on Python 3.7 at present, so I think we should be good to go.
