### ISSUE TITLE
SFMC Credit Card Expiration trigger testing and setup

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#264]
2 things related to the cc expiration trigger setup: 

(1) the trigger subscription-services-cc-expired has been created in the Basket Admin interface and when we tried to test it, we did not receive the email 

(2) we need to set up basket to automatically call this job ^ when it receives the credit card expiration event (Customer.Source.Expiring) from SubHub

Brynne is out the week of July 29 in onboarding, so Desiree can assist with testing as necessary.

**Comment by pmac** [comment]
What is the exact ID of the trigger in SFMC? Basket is setup to translate these, so it prepends the language to the front of the ID (e.g. "en_subscription_services_cc_expired"). I can make our job not do that, but it would be looking for the language version by default and that might be why the test didn't work.

**Comment by pmac** [comment]
And if basket is only going to be using this trigger internally then it doesn't need to be in the basket admin.
