### ISSUE TITLE
Partially populated records in Salesforce from SubHub

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#281]
There are partially populated records coming in to the Salesforce sandbox. Over the past 2 days, the following Opportunities have come in with various pieces of missing data. Here are a number of records and the data elements that are missing

 sub_Fa48bJRvTgmScp
 missing invoice number, cc last 4, cc type (brand), transaction id (i think we're missing data from invoice.finalized and payment.intent.succeeded events)
 
 sub_Fa5E9fhzvpmdtr
 missing service plan info (this would come from customer.subscription.created or customer.subscription.updated events)
 
 sub_FZkJ3J5z01wYn6
 Missing cc brand, cc last 4, service plan (missing data from payment.intent.succeeded, and either customer.subscription.created OR customer.subscription.updated - depending on if this is a new charge or a recurring transaction charge)
 
 sub_FZfmshfGP5iQiT
 missing invoice number, billing cycle start, billing cycle end, last 4 digits, cc type (brand)  (missing data from invoice.finalized and payment.intent.succeeded)

**Comment by pmac** [comment]
I believe we've solved this. We can reopen if we see it again.
