### ISSUE TITLE
Incorrect date - Sub Hub transactions

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#294]
There's an incorrect date issue on some records coming in from sub hub for new subscriptions. 

Sample transaction where the date was set incorrectly. One of the 3 events that is sending data over to Salesforce seems to be calculating the date incorrectly. 

sub_FcMxSdxTJPpgjp

I know for sure it's not in the payment.intent.succeeded event b/c I just watched one transaction w/out cc info (which is in that event) move from a funky date (7/23/19) to a correct date (8/13/2019)

I am thinking that this has to be either in invoice.finalized or customer.subscription.updated that it's going awry  and based on which event fires last, it will be correct or not

**Comment by desiree-mofo** [comment]
![image (2)](https://user-images.githubusercontent.com/27289391/63037925-16489600-be8e-11e9-8ecf-20eefb1c6588.png)
![image (1)](https://user-images.githubusercontent.com/27289391/63037927-16489600-be8e-11e9-9a1d-07c08156bd22.png)

**Comment by pmac** [comment]
Is this still an issue or was it fixed in the move to fewer events?

**Comment by pmac** [comment]
I believe this is fixed. Closing.
