### ISSUE TITLE
MDN Request to Integrate Basket<>Salesforce to support Opt-In Opt/Out flow

### ISSUE THREAD

**Issue by andrewmozilla** [mozmeao/basket#316]
Bugzilla Ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1562678

**Context**

General ask for integration: Connect MDN and Salesforce to support the opt-in flow for email so we are in legal compliance with our MDN communications. As of now we can only send the MDN userbase transactional emails since no automated opt-in flow is setup.

**Timeline:**
- Timeline Requested: Oct 30 at the latest
- In 2020 will be rolling out paid accounts (will be rolling out additional authentication options, i.e. Google).
- No paid product through 2019. Looking to provide a paid product in early 2020. Will also be looking to roll out new authentication options as well such as Google. (only auth option is Github at this time)

**CRM and MozMeao team would need to Support:**

- Brand new integration between MDN and Salesforce via Basket
- “Email me what’s new on MDN.” or “Get updates…” checkbox planned would opt you in to the marketing email program. [Along w/ agree to Terms checkbox] (Working with Michael Feldman already)
- Similar to AMO setup (but they are using FxA auth )
- Confirmation email (not needed since Authentication already happens)
- Welcome email needed
- Global sign-ups, EN only (no foreseeable plans to localize)

**Risks**
- Unless we authenticate with FxA it’s a blind spot for SubHub flow; will need to plug Basket into this (handle like petitions/ FxA newsletter opt-in part)
- 2020 planning (January launch); transition to FxA late 2020 or 2021 probably
- Concerns on timing for Andrew’s team & Pmac on integration/ Basket pieces (subscription setup should be doable); follow up with Dave?
- Havent seen a Basket (and) SubHub integration yet. Paid users go through SubHub (Subscription Services, only handles paid) integrated with CRM already - Service name changes if you’re Free or Paid (prioritize Paid).

**Comment by atopal** [comment]
That sounds correct to me. We need to be able to send marketing emails to people who have checked this box during their account registration.
