### ISSUE TITLE
Add Event ID and Event Name to SFDC integration

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#334]
Please add the event id and event name (both text (50) len + type) to the subscription services methods that are inserting and updating information in Salesforce for transactions.

**Comment by jpetto** [comment]
@desiree-mofo Confirming the request here - all Subhub data sent to Salesforce by basket should include the event id and event name? If so, what are the corresponding field names in Salesforce?

**Comment by desiree-mofo** [comment]
Field names are 
 Event_Id__c
 Event_Name__c
Both are Text(100) and are on the Opportunity object

**Comment by pmac** [comment]
@desiree-mofo are the names in the JSON data we receive `event_id` and `event_name` respectively? For which events are they sent?

**Comment by desiree-mofo** [comment]
@pmac  - they are sent on every event, but we only care about the ones hitting Opportunities (everything in the spreadsheet except contact_created) Spreadsheet linked below (which I just granted you access to) 
https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=331823332

The field names should be coming through into Basket as event_id and event_type. I've asked Marty to update the spreadsheet with that info so we have it on file if necessary.
