### ISSUE TITLE
SubHub events not making it to SalesForce

### ISSUE THREAD

**Issue by marty331** [mozmeao/basket#336]
@pmac 

SubHub is sending events and receiving a 200 response back from Basket, however these events are not making it to Salesforce.  Below are the payloads (somewhat scrubbed for privacy).

` {"message": "SENDING TO SALESFORCE", "lineno": 24, "pathname": "/var/task/src/hub/routes/salesforce.py", "levelname": "INFO", "threadName": "MainThread", "payload": "{\"event_id\": \"evt_1FPf2YKb9q6OnNsLAlR4uhPk\", \"event_type\": \"customer.created\", \"email\": \"marty@mozilla.com\", \"customer_id\": \"cus_FvW4QQq9hkqwRS\", \"name\": \"Martin Eleven\", \"user_id\": \"b3f0c53fc3db495f96105a378ac87a65\"}", "request_post": "<Response [200]>", "logger": "hub.app", "timestamp": "2019-10-04T00:53:02.693322Z"} `

`{"message": "SENDING TO SALESFORCE", "lineno": 24, "pathname": "/var/task/src/hub/routes/salesforce.py", "levelname": "INFO", "threadName": "MainThread", "payload": "{\"event_id\": \"evt_1FPf2ZKb9q6OnNsLotD8cqln\", \"event_type\": \"customer.subscription.created\", \"uid\": \"b3f0c53fc3db495f96105a378ac87a65\", \"active\": true, \"subscriptionId\": \"sub_FvW4zJwPSk1o17\", \"subscription_id\": \"sub_FvW4zJwPSk1o17\", \"productName\": \"F\", \"eventId\": \"evt_1FPf2ZKb9q6OnNsLotD8cqln\", \"eventCreatedAt\": 1570150383, \"messageCreatedAt\": 1570150384, \"invoice_id\": \"in_1FPf2YKb9q6OnNsL94OlVB4O\", \"plan_amount\": 100, \"customer_id\": \"cus_FvW4QQq9hkqwRS\", \"nickname\": \"F\", \"created\": 1570150382, \"canceled_at\": null, \"cancel_at\": null, \"cancel_at_period_end\": false, \"currency\": \"usd\", \"current_period_start\": 1570150382, \"current_period_end\": 1570236782, \"invoice_number\": \"10C26653-0001\", \"brand\": \"visa\", \"last4\": \"4242\", \"charge\": \"ch_1FPf2ZKb9q6OnNsLj0dgEm1b\"}", "request_post": "<Response [200]>", "logger": "hub.app", "timestamp": "2019-10-04T00:53:04.734233Z"} `

**Comment by marty331** [comment]
@jgmize pushed a commit last night that seems to have resolved this issue.
https://github.com/mozmeao/basket-config/compare/2acd6cf3ad41...e529bec7dbe6

**Comment by jgmize** [comment]
Thanks @marty331. As I commented in slack, while looking through the logs for clues on this issue I noticed that the basket-dev worker in oregon-a was getting repeatedly killed due to running into memory limits, so I [increased the limits in oregon-a](https://gitlab.com/mozmeao/basket-config/commit/2acd6cf3ad41dcf92e1c469ee97b526e4bdf4afb) and then [copied those limits to the worker in oregon-b](https://gitlab.com/mozmeao/basket-config/commit/e529bec7dbe60d3fb815e2853a3e856a0ee771f8).

**Comment by jgmize** [comment]
@pmac reported yesterday that we were still , and in response I [doubled the requests & limits](https://github.com/mozmeao/basket-config/commit/829ff8b3b9be6a33f59d29dafe92e4d87d525853), which appeared to alleviate the issue, but 
@jackiemunroe reported via slack that this problem has continued to intermittently recur, and searching through the logs I found more instances of the basket workers being SIGKILLED. I believe the next logical step is to add a [CELERY_WORKER_MAX_MEMORY_PER_CHILD](http://docs.celeryproject.org/en/latest/userguide/configuration.html#worker-max-memory-per-child) to our settings with a lower limit than the k8s deployment limit.

**Comment by pmac** [comment]
I believe we've solved this. We can reopen if it happens again.
