### ISSUE TITLE
New SubHub Event to monitor - when Fx Acct is deleted, cancel subscription

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#340]
When a user deletes their Firefox Account, we need to send that info to Salesforce so that we can send a cancellation email to them. 

The mappings are similar to the cancellation of a subscription and can be found here: 
https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=2141319461

The main difference is the Sales Stage, which will be set to "Account Deleted"

**Comment by pmac** [comment]
@desiree-mofo I don't have access to that spreadsheet.

**Comment by desiree-mofo** [comment]
@pmac - shared with both of your Google ID's (my apologies)

**Comment by pmac** [comment]
So I should add this opportunity object when I get the event from FxA that the account has been deleted, or there will be a new event from subhub for this?

**Comment by desiree-mofo** [comment]
The event to look for is customer.deleted - it's a new event that SubHub is sending over

**Comment by pmac** [comment]
Any details on what data might be in that event?

**Comment by desiree-mofo** [comment]
the mappings are in the spreadsheet (https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=2141319461) on the "Deletion of FxA" tab - the stripe fields are mapped and any values you'll need to set in SFDC as defaults are listed there as well

**Comment by pmac** [comment]
got it. sorry I missed that bit. thanks!
