### ISSUE TITLE
Fx Account flow testing in Salesforce - ensure reactivation of an account flows properly

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#341]
With the config of the deletion of a Firefox Account for subscription services, we will be automatically checking a flag on the Contact record to denote they've deleted their Firefox Account. A few things that may impact Basket: 

(1) the case when someone deletes a Fx Account and does not have an active subscription - how will Salesforce know about that? (right now it's logging in a SFMC data extension, but going forward we will have a checkbox on the Contact record to denote they've deleted their account)

(2) If someone re-creates another Fx Account using the same email address after deleting their Fx Account, we should ensure that the new Fx Account flow checks to make sure the checkbox is NOT equal to true and if it is, set it to false

**Comment by desiree-mofo** [comment]
API name of field to check on Contact is : FxA_Account_Deleted__c

**Comment by pmac** [comment]
Is that field in ADVO and ready for testing? I can get that working. 

The only info I get from FxA when an account is deleted is an FxA ID, so I can only flip that switch if SFDC already has a record of that FxA ID. Is that okay, or should I create an empty record with just that FxA ID and that flag flipped?

**Comment by desiree-mofo** [comment]
Field is on ADVO and basket-stage has the ability to write to it. 

The question on what to do if an FxA doesn't exist yet is a good one. Let me check with Andrew and we'll get back to you. It will probably be a moot point (hopefully) depending on when the Firefox Accounts get moved over to SFDC from SFMC

**Comment by pmac** [comment]
Should I add flipping this flag to the handling of the `customer.deleted` event from #340 ?

**Comment by desiree-mofo** [comment]
Yes, please add it to that event as well - flip the "Fx Account Deleted" flag to true when that comes in from SubHub
