### ISSUE TITLE
Salesforce Record Type ID: Production - Subscription Services

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#342]
Prior to launch, we need to ensure that Basket code is updated to include the record type ID for the Salesforce Production instance. The record type ID for Subscription Services Opportunities in the Salesforce Sales Cloud Production instance is:  0124O000000R0ODQA0

The sandbox record type id is: 012R0000000dQ4dIAE (as a reference)

Please make sure the code is updated to point to the proper record type ID prior to October 11, 2019. 

Thank you!

**Comment by pmac** [comment]
I have filed a PR for this https://github.com/mozmeao/basket-config/pull/39

**Comment by pmac** [comment]
Above PR has merged and deployed. This is done.
