### ISSUE TITLE
Allow for pass-through of a country param for mozilla-foundation newsletter

### ISSUE THREAD

**Issue by youriwims** [mozmeao/basket#346]
We would like added support to get a user's country, based on the `country` property and it doesn't look like basket is currently expecting that data.

Related Ticket #344, https://github.com/mozilla/foundation.mozilla.org/pull/3700

**Comment by pmac** [comment]
My apologies. I told you wrong. Basket is already looking for `country` in the data and if it's sent will store it for the contact. Thanks for filing!
