### ISSUE TITLE
Firefox Private Network Waiting list

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#353]
We need a flow into Salesforce from the Firefox Private Network waiting list form (Ricky Rosario is the FxA engineer working on that). A campaign member record needs to be created in Salesforce based on a form submission. (This is similiar to how we store petition signatures in Salesforce for the Foundation). 

Campaign Id's are included: 701R0000000ioSzIAI (ADVO) and 7014O0000016Vp7QAE (PROD)

Upon form submission, please query based on the email address on the Contact object for an existing contact w/ a matching email address. If found, grab the Contact Id of the contact and insert a new record into the Campaign Member object with ContactId = ContactId returned in the query, Campaign ID = (above value, based on environment), I've configured default status values, so no need to set those. 

We *may* also need to pass through 2 fields - country and platform, but I'm waiting to see if they can send those to us and if so, I'll update the issue here to include the API Names of those fields.

**Comment by pmac** [comment]
We've decided to go with simply a new boolean field in SFDC for this. Then we can simply treat this as a newsletter and the existing subscribe API will work for this.
