### ISSUE TITLE
SubHub > Salesforce integration update to process reactivated subscriptions

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#362]
Update basket to accept new event type for reactivated subscriptions. Mappings can be found here ("Reactivation" worksheet) (https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=962422475

Jackie will let us know when the payload is ready to be tested. 

Desiree will update SFDC's sandbox to include the new stage name

**Comment by desiree-mofo** [comment]
Stage name of "Reactivation" added to the ADVO sandbox in preparation for testing.

**Comment by jackiemunroe** [comment]
PR for SubHub implementation: https://github.com/mozilla/subhub/pull/330
