### ISSUE TITLE
SubHub > Salesforce integration to accept subscription upgrades and downgrades

### ISSUE THREAD

**Issue by marty331** [mozmeao/basket#371]
Update basket to accept new event types - `customer.subscription.upgrade` and `customer.subscription.downgrade`.  Mappings can be found here:  https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=1497563275 and here
https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=813168994

@marty331 is making the changes on Subhub

**Comment by pmac** [comment]
A few questions from the doc:

1. The new Opportunity fields seem to be all lower case when all of the other fields have been title case. I find naming consistency to be very helpful normally. Is this an issue with the doc or have we decided to go another way with naming?
2. It says the value for `StageName` will differ based on the event but I don't see any info about what those will be yet.
3. There is no Opportunity field specified for the `proration_amount` value. Should I ignore that or is a new field forthcoming?

I've got a good start on the bits not mentioned above. Once we get answers to these questions I should be able to quickly get a PR filed.

**Comment by marty331** [comment]
@mozbrandon can you address the questions above around the Opportunity field naming, StageName and proration_amount?

Thanks!

**Comment by mozbrandon** [comment]
@pmac There are multiple issues with the document that was provided to us and I hope these answers will allow you to move forward.

1. Please keep using title case.
2. For a Subscription Downgrade, set `Stagename` to Subscription Downgrade. For a Subscription Upgrade, set `Stagename` to Subscription Upgrade.
3. Added field `Proration_Amount__c` to Advo.

**Comment by marty331** [comment]
@pmac I updated the spreadsheet to reflect the title case.

**Comment by pmac** [comment]
Thank you both 🥇 I should have a PR in for this today.
