### ISSUE TITLE
SubHub > Salesforce integration to modify customer.recurring_charge payload

### ISSUE THREAD

**Issue by marty331** [mozmeao/basket#378]
Update basket to add new fields to customer.recurring_charge payload. Mappings can be found here: https://docs.google.com/spreadsheets/d/1z6aXj_9GUpl5g_hR2k_SmjY5tyhxvnoHGOr8e-cbo18/edit#gid=1328177684

@marty331 is making the changes on Subhub
Brandon P will need to fill in the field for the total amount mapping in SF.

**Comment by pmac** [comment]
Are these different updates than #374 ?

**Comment by pmac** [comment]
If not can you indicate here which fields are new and/or updated?

**Comment by marty331** [comment]
@pmac yes these are different than #374 and I just updated the sheet to show the two new fields which are proration_amount and total_amount.

**Comment by pmac** [comment]
Is this it? I'd like to avoid a flurry of small updates and just knock them all out at once if possible.

**Comment by pmac** [comment]
This change is now deployed to dev. @mozbrandon can you let me know when the new fields are available in prod so I can safely deploy?

Thanks!

**Comment by pmac** [comment]
I had to revert this change in d4786007d40256478e0be04abc1a4a77ec2188b9 due to these fields not yet being ready in SFDC prod. We'll add them back when ready.
