### ISSUE TITLE
Pass through 2 Additional Fields to SalesForce CRM from FxA Form

### ISSUE THREAD

**Issue by andrewmozilla** [mozmeao/basket#384]
Hola PMac.

I would like to request that we collect both Geo and Platform when someone submits their interest for the FPN product. We currently were only collecting email. 

The two fields are:

  | "FPN Waitlist Geo" | API Name: FPN_Waitlist_Geo__c |   | Text(120) |

  | "FPN Waitlist Platform" | API Name: FPN_Waitlist_Platform__c |   | Text(120) |

This is ready in Prod.

**Comment by pmac** [comment]
PR filed. The new parameters for the `/news/subscribe/` endpoint are:

* `fpn_country`
* `fpn_platform`

@rlr
