### ISSUE TITLE
Capture credit card type in MoFo donations

### ISSUE THREAD

**Issue by alanmoo** [mozmeao/basket#386]
(MoFo work tracked [here](https://github.com/mozilla/donate-wagtail/issues/620))

We need to capture credit card type in donation opportunity records so that we can include it in emailed receipts to donors. It sounds like we need to

a.) add the `Credit_Card_Type_c` field to the donation opportunity record type so that MoFo users can see the value.
b.) record the type when passed to Basket. I'm not sure if it needs to be a new key in the Basket payload or additional options for payment method, and I don't have an opinion. But whatever key we use should be able to not exist or be an empty string (or null?) like other optional fields already are.

**Comment by pmac** [comment]
Sounds good. As soon as y'all determine the key for this value I'll get a PR going.

**Comment by alanmoo** [comment]
The key that we use to pass in to Basket? I'd assume `card_type` should be fine? @pomax @stephaniemcv any concerns with that? It still gets passed to the same spot in Salesforce regardless of the name.

**Comment by pmac** [comment]
Yes. I just need to know what it'll be.

**Comment by Pomax** [comment]
Based on the data from Braintree, `card_type` looks right to me.

**Comment by pmac** [comment]
Is this for all of the donation event types, or just the initial `donation` type?

**Comment by Pomax** [comment]
As far as I know, only for donations, so that we can add that information to donation receipt emails.

**Comment by alanmoo** [comment]
I believe this needs to work for recurring donations too.

**Comment by pmac** [comment]
> I believe this needs to work for recurring donations too.

I think recurring donations are represented by an Opportunity object in SFDC for each donation with `Payment_Type__c == 'Recurring'`. So it's still just `donation` events we need to worry about in basket. The other donation event types seem to all deal with updating an Opportunity to indicate it was canceled for some reason.

**Comment by stephaniemcv** [comment]
Pmac is correct.

**Comment by pmac** [comment]
Based on [this comment](https://github.com/mozilla/donate-wagtail/issues/620#issuecomment-558872914) the value could be the string `"None"`. What should basket record in that case?

**Comment by stephaniemcv** [comment]
Can Basket record "none"? The field in Salesforce is text 25. I'm assuming this scenario would happen with Braintree processing Paypal as those transactions don't have a card type. Subscription Services wouldn't have designed for this since they're taking only Stripe right now.

**Comment by pmac** [comment]
Yeah. Letting whatever value it is pass through is the easiest thing for me for sure :)

**Comment by Pomax** [comment]
I can change it to the string `Unknown` instead, so that it lines up with the value the braintree has for credit cards in general
