### ISSUE TITLE
Lookup new SubHub users by FxA ID first

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#395]
We currently encounter errors when a user comes in via SubHub with an email address and FxA ID, but another contact in Salesforce already has that FxA ID. This can happen due to the user changing their FxA email address at some point. To combat this @mozbrandon, @andrewmozilla, and I discussed solutions and decided on the following:

Look up users by FxA ID first. If a record is found:

* If the email matches the one FxA sent us, then we've found the right record and can continue on.
* If the emails don't match then we update the contact found above to have the `FxA_Id__c` field contain `DUPE:<fxa_id>` and set the `FxA_Account_Deleted__c` field to `True`. We then need to look up the FxA email to see if there's a contact for that email.
  * If there is a contact for the FxA email then fetch it and update it to have the correct FxA ID.
  * If there is not a contact for the FxA email then create one

I think that's it. @andrewmozilla please correct me if I'm wrong.

**Comment by andrewmozilla** [comment]
This sounds good PMac!

**Comment by andrewmozilla** [comment]
Last comment, I believe we discussed that this change would only apply to Subscription Services (purchase/customer) events. Is that true?

**Comment by pmac** [comment]
That's correct. Thanks!
