### ISSUE TITLE
Additional fields for FxA to CRM feed. 

### ISSUE THREAD

**Issue by LaurenNiolet** [mozmeao/basket#454]
This new issue is to cover additional fields related to the feed established in https://github.com/mozmeao/basket/issues/405

When new accounts are created, we'd like to have all fields currently included on the Firefox_Account_ID table added to the CRM record. 

That would be 

FXA_ID
Created Date
Language
EmailAddress
Service

My understanding is that currently FxA ID and email address are already sent. So the remaining fields would be additional.

**Comment by pmac** [comment]
We already handle fxa_id, created date, language, email, and service. I apologize for not realizing this before commenting on #405. I think we're done, but I'll let @andrewmozilla confirm.

**Comment by mozbrandon** [comment]
@pmac Lauren is referencing the date a Firefox Account is created not the created date standard field in Salesforce. 

@LaurenNiolet Is this field a date or date/time field?

**Comment by pmac** [comment]
> Lauren is referencing the date a Firefox Account is created not the created date standard field in Salesforce.

@mozbrandon right. it's a field called `FxA_Created_Date__c` which you created. See https://github.com/mozmeao/basket/issues/149#issuecomment-525018546

**Comment by mozbrandon** [comment]
@pmac thanks for the correction. In that case I believe this issue can be closed.

**Comment by mozbrandon** [comment]
Update: this field has not been deployed to sfdc prod yet.

**Comment by pmac** [comment]
I heard this is in prod now, so I think we can close this. Thanks all.
