### ISSUE TITLE
Update FxA Created Date in SFMC based on timestamp data in verified events

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#472]
In #77 we added support for a `createDate` from FxA. They no longer send that field with `verified` events. There are a few other fields that do come with the events that could potentially work. For example, the data looks like this:

```python
{
  'country': 'United States', 
  'countryCode': 'US', 
  'email': 'sync0.3486440592016071@restmail.net', 
  'event': 'verified',
  'iss': 'api-accounts.stage.mozaws.net', 
  'lang': 'en', 
  'locale': 'en', 
  'metricsContext': {
    'flow_time': None, 
    'time': '** ** ** **'
  }, 
  'timestamp': '** ** ** **', 
  'ts': 1582252410.066, 
  'uid': 'dac5bf77929745668ca44ea392e35a4c', 
  'userAgent': 'node-XMLHttpRequest'
}
```

So it looks like `metricsContext['time']`, `timestamp`, or `ts` values could work. I've asked in https://github.com/mozilla/fxa/issues/4138 which would be the best and most reliable one to use. Once we find out we should be able to finish #125.

cc @desiree-mofo

**Comment by pmac** [comment]
@desiree-mofo you can see in the linked FxA issue that I believe that the `ts` value (above) is the best one we have. All three of the ones I was looking at are just the time of the task creation if I'm reading the FxA code correctly. So we can use that one and call it "good enough" IMHO. Let me know what you think. I've got a PR in to use `ts` (linked above).

**Comment by desiree-mofo** [comment]
@pmac  - has anyone on the FxA side confirmed what the 'ts' value represents?

**Comment by pmac** [comment]
No, but I found where it's set here:

https://github.com/mozilla/fxa/blob/9c39cc49172c2cb1eb92bd1d232ef3e3cc957dc8/packages/fxa-auth-server/lib/log.js#L139

**Comment by pmac** [comment]
They have now confirmed that the `ts` value should work well for us. I'm going to merge the PR.

**Comment by pmac** [comment]
This change is now deployed to basket-dev, so we should start seeing fxa created date being populated in ADVO.
