### ISSUE TITLE
Investigate new task queue system

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#477]
As we've seen recently (#474, #473, #469) celery is overly complex and tricky for what we need, which is simply a good way to execute calls to Salesforce (currently) in a reliable, asynchronous, and fault-tolerant way. The front runners for replacement are these:

* [RQ](http://python-rq.org/)
  * is a mature project and well supported
  * has a [vibrant community](https://github.com/rq/rq)
  * is the choice of the redash project at Mozilla
  * has a good [django integration library](https://github.com/rq/django-rq)
  * has a [good scheduler](https://github.com/rq/rq-scheduler) for future jobs and recurring jobs
  * CON: does not have a native retry concept, we'd have to build it using the scheduler
* [Spinach](https://spinach.readthedocs.io/en/stable/)
  * young project
  * very well designed API for use IMO
  * uses redis lua scripts for much of the work
  * includes django integration, scheduling, and retrying
  * not much community around it

So I'm leaning toward RQ mostly because it seems to be the safe and well supported bet, but I must say that reading Spinach's docs is a pleasure and I love it's design.

@glogiotatidis @metadave @duallain thoughts?

**Comment by pmac** [comment]
@jezdez I'm curious about your opinion here as well and whether I've presented the options fairly.

**Comment by pmac** [comment]
More context in this [Redash issue](https://github.com/getredash/redash/issues/4092).

**Comment by pmac** [comment]
I've gotta say that despite it's youth and community, I'm leaning toward Spinach for [all the reasons](https://github.com/getredash/redash/issues/4092#issuecomment-523814991) outlined by @jezdez in the linked issue.

**Comment by glogiotatidis** [comment]
Spinach indeed looks promising. My understanding is that it should be easy to implement in basket which makes this a low cost investment if we want to try out. 

It seems that it requires a persistent Redis instance and I see that AWS provides this functionality through Redis backup / restore which I want to confirm that it's automated and streamlined. @duallain maybe you know more?

Does our current -celery based- setup use the DB for state storage?

**Comment by pmac** [comment]
> Does our current -celery based- setup use the DB for state storage?

It's all Redis as far as I know.

**Comment by metadave** [comment]
> It seems that it requires a persistent Redis instance and I see that AWS provides this functionality through Redis backup / restore which I want to confirm that it's automated and streamlined. 

`ee-redis-rg-usw` does not appear to have Terraform automation :-(

**Comment by metadave** [comment]
@pmac ok to close this for now?

**Comment by pmac** [comment]
Yeah. Good call. We're stable now.
