### ISSUE TITLE
Email preferences page shows a "Get a Firefox account" button while the user is already logged in

### ISSUE THREAD

**Issue by ioanarusiczki** [mozmeao/basket#504]
STR:
1. With an already created Firefox Account I went into settings and clicked the "Email preferences"  at the bottom of the page which redirects to the newsletter page https://www.mozilla.org/en-US/newsletter/
2. Observe the blue button on the top right
3. Click the button

Actual result:
It redirects to https://www.mozilla.org/en-US/firefox/accounts/  

Expected result:
The button should have another name since the user is already created. Instead of "Get a Firefox Account" maybe "Go to Firefox accounts". 

Notes:
I tested on 75.0b3(Win10). 

![button not good](https://user-images.githubusercontent.com/33448286/76625080-33863580-653f-11ea-9f33-e0f1d627f86e.gif)

**Comment by pmac** [comment]
www.mozilla.org has no way of knowing that you're logged into accounts.firefox.com. You can try filing this in the [repo for the www.mozilla.org website](https://github.com/mozilla/bedrock/issues), but I believe they're already doing everything they can to detect an account and hide that button.
