### ISSUE TITLE
Process `newsletters:update` FxA event to restore newsletters in Sync signup

### ISSUE THREAD

**Issue by vbudhram** [mozmeao/basket#523]
Basket currently processes FxA `verified` events to subscribe newsletters to users. This flow was changed for sync when we switched newsletter options with choose what to sync option in https://github.com/mozilla/fxa/pull/1206.

In https://jira.mozilla.com/browse/FXA-1462, we proposed to add the newsletter subscription at the end of the sync signup flow. To support this, FxA can emit a new event when the user selects the newsletters. This event should emit values similar to the `verified` event.

Ex. Newsletter sqs update event
- `event`: The string "newsletters:update"
- `uid`: The userid of the account being that was created.
- `email`: The primary email address that was verified for the account.
- `locale`: The accept-language header supplies by the user at account creation.
- `country`: The estimated country (based on IP) of the user
- `countryCode`: The country code of `country`
- `newsletters`: Array of newsletter subscriptions for a user
- `userAgent`: The user agent of device that completed the account verified

**Comment by pmac** [comment]
Looks good. Thanks @vbudhram !
