### ISSUE TITLE
Store FxA Primary Email Change in SFDC

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#532]
We currently store these events in SFMC in a data extension, but we should store the new email in the CRM. We've decided to create a new field (e.g. `FxA_Primary_Email__c`) for the changed email. This is related to #522 since AMO uses FxA for auth and gets their email addresses from FxA. 

After this is done we'll need to load the past email changes stored in the data extension in SFMC into the CRM.

/cc @andrewmozilla

**Comment by glogiotatidis** [comment]
Adding the new `FxA_Primary_Email__c` field means that we keep the existing `email` as is and we only update this new field? In other words, why do we need a new field since we already store emails?

**Comment by pmac** [comment]
This is for when people change their primary email in FxA, but if we change their primary contact email then everything would change, and we don't inform them of that yet. So this is a way to let us use their primary FxA email for FxA stuff and the original one for other things (e.g. newsletters, donations, etc.). It's just how the email folks want to handle it for now.

**Comment by glogiotatidis** [comment]
Code is merged, IIRC we left this open to migrate the pre-existing FxA SFMC entries to SFDC?

**Comment by pmac** [comment]
No, I think we can close this. Thanks for the reminder.
