### ISSUE TITLE
SubHub has changed the format of all messages

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#536]
The subhub team deployed a change sometime before May 22nd that resulted in the format of all of the messages sent to basket via POST requests to the `/subhub/` URL to be different. Due to the JSON schema changing basket can no longer recognize any of the data or the message types, and can no longer send the messages to the right task for processing. If it were able to route the messages the data would not be in the format the tasks recognize either. 

One result of this is that all requests from SubHub to basket have been returning 500 errors since the 22nd (see the [sentry error](https://sentry.prod.mozaws.net/operations/basket-prod/issues/8521744/?query=is%3Aunresolved)).

The primary result of this is that no new SubHub data has been recorded in Salesforce since at least the 22nd of May.

**Comment by pmac** [comment]
I've been in discussions on Slack with the Salesforce team and they tell me that this will be resolved on the SubHub side by them rolling out changes that directly integrates SubHub with Salesforce. 

Since the request from that team does not include changes to basket, I have deployed changes in 0ced7ae62ca238b32aab9f517afb88c4f0cf7fae that causes basket to no longer send 500 errors and log exceptions, but to instead send 400 responses with the more appropriate `unknown event type` message.

**Comment by metadave** [comment]
cc @bensternthal

**Comment by pmac** [comment]
Subhub has now stopped sending data to basket at all. Without informing us of any of these changes. I believe we can safely remove all of the subhub related code now.
