### ISSUE TITLE
Only synchronize AMO developers to basket

### ISSUE THREAD

**Issue by diox** [mozmeao/basket#564]
We only want AMO data in Salesforce for developers, not all AMO users.

- When an add-on sync is triggered, existing authors info for that add-on in Salesforce needs to be checked to remove authors that are not part of the new sync data: those users are no longer authors of the add-on.
- User sync requests that don't match an user that is already in Salesforce should be ignored. New users should only come from an add-on sync authors data, the user sync should only be used to update existing users.

In addition, we need to handle deletion, so:
- AMO data for users marked as deleted in AMO need to be removed periodically
- Deleted add-ons need to be removed periodically
- AMO data for users with only deleted add-ons or no add-ons left should be removed periodically
- Add-ons with only deleted users left as authors should be removed periodically

**Comment by pmac** [comment]
I've got the first 2 points done. The deletion stuff seems more tricky. 

> AMO data for users marked as deleted in AMO need to be removed periodically

This just means removing the AMO_ID from the user when we get a user update that includes `"deleted": true` right?

> Deleted add-ons need to be removed periodically

I'm not currently looking for deleted for addons. Should I just expect a boolean `"deleted"` field in the addon data like I do for the users?

> AMO data for users with only deleted add-ons or no add-ons left should be removed periodically

I'm guessing this should happen whenever an addon is deleted? I can lookup all of the users and check their other addons. That query might not work very well from basket though. Can you send a request to delete a user that no longer has active users?

> Add-ons with only deleted users left as authors should be removed periodically

Similar to above. It'd be a lot easier for salesforce and basket if you could just let us know which addons to delete.

**Comment by diox** [comment]
> I've got the first 2 points done. The deletion stuff seems more tricky.
> 
> > AMO data for users marked as deleted in AMO need to be removed periodically
> 
> This just means removing the AMO_ID from the user when we get a user update that includes `"deleted": true` right?

Yes

> > Deleted add-ons need to be removed periodically
> 
> I'm not currently looking for deleted for addons. Should I just expect a boolean `"deleted"` field in the addon data like I do for the users?

Add-ons are a bit special in that regard, the field you should look for is `status` with the value `deleted`.

> > AMO data for users with only deleted add-ons or no add-ons left should be removed periodically
> 
> I'm guessing this should happen whenever an addon is deleted? I can lookup all of the users and check their other addons. That query might not work very well from basket though. Can you send a request to delete a user that no longer has active users?

This can happen when the add-on is deleted but also when someone is removed as an author from an add-on. It's quite tricky to do on AMO side (where users with no add-ons are a normal thing). My thought was, if you are doing the cleanup from the first point, removing the "link" between an add-on with a user when the user is removed from the authors of the add-on, then eventually you'll end up with orphaned users with no "link" to any add-ons, and we should be able to do a query to remove those periodically ? Doesn't necessarily need to be fully automated, as long as we have a way to purge them (and avoid them when sending communication to developers).

> > Add-ons with only deleted users left as authors should be removed periodically
> 
> Similar to above. It'd be a lot easier for salesforce and basket if you could just let us know which addons to delete.

Actually this one should be fine - the add-ons should get deleted on AMO's side when that happens so you'll get the notification.

**Comment by pmac** [comment]
> Add-ons are a bit special in that regard, the field you should look for is `status` with the value `deleted`.

We are storing the `status` field value in the addon record. Should we fully remove those records or keep them for info and use the `status` field as a filter for mailing?

**Comment by diox** [comment]
Fully remove - they are soft-deleted on AMO because we need to keep them for a while, but as far as Salesforce is concerned they shouldn't exist anymore.

**Comment by pmac** [comment]
Hopefully last question. When marking a user as no longer an AMO user e.g. when their last addon is deleted, what should that record look like. I have 3 fields I'm curious about. I'm thinking it should be the following, but perhaps some of these should be left alone?

```python
{
	"AMO_User": False,  # this is true for anyone who has come through AMO, should it be false?
	"AMO_Deleted: True, # this is false until the user is deleted, should we make it `True` in this case?
	"AMO_Id": None,      # this should be cleared out I'm pretty sure
}
```

That's it. I'm just asking what the state of these three fields should be when I remove AMO data from a contact when they no longer have addons. We might want to keep `AMO_User` true to indicate that they were once an AMO user, or maybe we don't care, and I'm not sure if `AMO_Deleted` is only to indicate that the user account itself has been deleted.

**Comment by diox** [comment]
`AMO_Deleted` shouldn't be touched: the user technically hasn't been deleted, and they could re-create/be added as an author to add-ons again.

Regarding `AMO_Id` and `AMO_User`, I think we want to clear `AMO_User` to ensure the user is never considered an AMO developer again when making queries to send the newsletter etc, and keeping the `AMO_Id` might be helpful if they become a developer again and we have to re-synchronize the data ?

**Comment by pmac** [comment]
>  keeping the `AMO_Id` might be helpful if they become a developer again and we have to re-synchronize the data ?

If they get synced again we'd look them up via the FxA_Id and add the AMO_Id again. So I think it's fine either way. Above when I asked `This just means removing the AMO_ID from the user when we get a user update that includes "deleted": true right?` you said `yes`, so I thought we would be removing `AMO_Id` whenever we wanted to no longer associate the user as an AMO developer, but because we have `AMO_User` we don't have to do that. Either way I think we should be consistent.

**Comment by diox** [comment]
Ah right, it's fine either way.

**Comment by pmac** [comment]
Okay. This is merged and will be on basket-dev shortly. We can QA again.
