### ISSUE TITLE
Internal Server Error received when trying to login on Mozilla email preferences

### ISSUE THREAD

**Issue by vasilicatamas** [mozmeao/basket#600]
**Build:**
Stage [Train 1.191.1]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Login using a stage account and navigate to the Manage Account page.
2. Click "Email preferences" link displayed at the bottom of the page. 
3. Click on the "Sign in" button.

**Expected results:**
The user is successfully connected to "Manage your Email Preferences" page.

**Actual Results:**
- Most of the times is received the following error:“Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.”
- Sometimes appears the following error: “We are sorry, but there was a problem with our system. Please try again later!”

**Additional notes**
This issue is not reproducible on production.

![Screenshot_33](https://user-images.githubusercontent.com/18114210/95740260-db5e1000-0c94-11eb-9367-87415da79d75.png)
![Screenshot_34](https://user-images.githubusercontent.com/18114210/95740265-dbf6a680-0c94-11eb-8a71-4122e164f05f.png)

**Comment by clouserw** [comment]
Thanks @pmac

**Comment by chenba** [comment]
> I see Unknown code errors in Sentry. Perhaps FxA stage is not sending us the right codes?

The code for generating those authorization codes hasn't change in a long time.  Moreover, dev AMO (which uses stage FxA) appears to be work, so not all auth codes are failing.

Not sure what's going on.  :(

**Comment by jbuck** [comment]
I tried this in stage again, and the behaviour seems to have changed to a 30s timeout error. Based on sentry, it's possible that a salesforce dependency upgrade may be causing this issue - @pmac is investigating

**Comment by pmac** [comment]
Found it. It was an error introduced recently that was causing basket stage to attempt to login to a sandbox instance of SFDC. This is now fixed in 88680e4b289940f79ceca11d2b55cb9559b3733e and basket stage is working normally again.

**Comment by vasilicatamas** [comment]
I confirm that the error is no longer received and the Mozilla email preferences page is successfully opened. Tested on Stage [Train 1.192.0].

![Screenshot_46](https://user-images.githubusercontent.com/18114210/96997278-28b26b00-153a-11eb-8fce-153865e4a3cf.png)
