### ISSUE TITLE
Send Data to Acoustic

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#624]
Instead of putting various data into SFMC Data Extensions, we'll need to put it into Acoustic.

Many outstanding questions remain for this one:

- [ ] Where exactly in Acoustic?
- [ ] What data exactly? Only the FxA activity?

**Comment by pmac** [comment]
@jbuck that last question is probably one for you ☝️

**Comment by jbuck** [comment]
@pmac TBH, the FxA logs already live in BQ, so you can query them directly whenever you want. If a table of active daily users is something you want that should be easy to setup a scheduled query

**Comment by pmac** [comment]
And these logs are pretty much the same data as in the files basket is processing today?

**Comment by jbuck** [comment]
Exact same source data, yeah

**Comment by pmac** [comment]
Looks like we'll be sending most of these data directly to Acoustic instead of BQ.

**Comment by pmac** [comment]
We've completed this 🎉
