### ISSUE TITLE
Internal server error received while logging for the first time on Mozilla email preferences page

### ISSUE THREAD

**Issue by vasilicatamas** [mozmeao/basket#650]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit

**Steps to reproduce**
1. Login using a valid Firefox account on https://accounts.stage.mozaws.net
2. Click "Email preferences" link displayed at the bottom of the page.
3. Click on the "Sign in" button.

**Expected results:**
“Manage your Email Preferences” page is successfully displayed.

**Actual Results:**
“Internal Server Error.
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.” error is received.

**Additional notes:**
- This issue reproduces only at the first login attempt.
- This issue is not reproducible in production.

![Screenshot_15](https://user-images.githubusercontent.com/18114210/106585891-7e8eaa00-6550-11eb-8d49-f6c6083939df.png)

**Comment by robhudson** [comment]
Currently works for me. Please re-open if you continue to encounter this error.
