### ISSUE TITLE
Send subscription cofirm emails via Acoustic Transact

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#669]
* Send the right message based on the newsletter:
  * `mozilla-foundation` gets the mofo message
  * All others get the moco message
* Only send if the newsletter is marked in the DB as needing double opt in.
* Only send if the user hasn't already opted in.
* Send in the users prefered language if we have a meessage in that language, otherwise send in English

**Comment by pmac** [comment]
Outstanding questions:

* If we get multiple newsletters in the subscription request (can often happen from email pref center or some forms) and there are both mofo and moco newsletters, which do we send?
* Are we sure it's only `mozilla-foundation` subscriptions that should get the mofo confirm?

**Comment by stephaniemcv** [comment]
MoFo confirm should happen for sub_mozilla_foundation, sub_internet_health_report, sub_mozilla_fellowship_awardee_alumni, sub_mozilla_festival and sub_common_voice (once it's unbundled from its newsletter grouping in Basket.

**Comment by krattliff** [comment]
If we get multiple newsletters in the subscription request (can often happen from email pref center or some forms) and there are both mofo and moco newsletters, which do we send? 

How about sending the confirmation for the first subscription signed up for? If new subscribers have signed up for multiple subscriptions, those will all be double-opted-in after the new subscriber has clicked confirm within the email.

**Comment by pmac** [comment]
Yeah, we should only need to send one confirm, but my question is which confirm to choose if multiple subscriptions come in with the request? It's probably unlikely, but it is possible to have a first subscription come in with `newsletters=mozilla-foundation,firefox-ios` for example. Should I just choose the first in the list and go with that, or should one of the confirms be the default in these situations?

**Comment by stephaniemcv** [comment]
My 2 cents is that the Mozilla branded confirm should be the default since newsletter subscriptions is a "pan-Mozilla" project, especially since I think pmac is right, this is probably not a very likely scenario.

**Comment by pmac** [comment]
Yeah, this is an edge case to be sure, I just have to code for it just in case.
