### ISSUE TITLE
[FxA-Settings] Internal Server Error received when trying to login on Mozilla email preferences

### ISSUE THREAD

**Issue by vasilicatamas** [mozmeao/basket#675]
**Build:**
Stage [Train 1.203.2]

**Affected platforms:**
Windows 10 64-bit
Android 9

**Steps to reproduce:**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Email communications" option displayed in the navigation menu.
3. Click on the "Sign in" button.

**Expected results:**
The user is successfully connected to the "Manage your Email Preferences" page.

**Actual Results:**
“500 - Internal Server Error - Basket” error is received - [page url](https://basket.allizom.org/fxa/callback/?code=f811d6b894ed82108e3ddae60e108d14860bafb266812284b05c222af6555fed&state=1256ffcb19a0cffc056547afe611eae9&action=signin).

**Additional notes**
This issue is not reproducible on Prod [Train 1.202.3].

![Screenshot_37](https://user-images.githubusercontent.com/18114210/112971555-00b5dc00-9158-11eb-848b-5874de1a66c1.png)

**Comment by pmac** [comment]
Not sure what's up. I can't reproduce at the moment. Could be that Salesforce was having trouble at the time. I'll check Sentry.

**Comment by pmac** [comment]
Seems it was a short-lived DB issue during a deployment. All seems fine now.

**Comment by vasilicatamas** [comment]
I am still able to reproduce this issue on Stage [Train 1.203.4] under Windows 10 64-bit and macOS 10.14.6 using both old and new users on both dirty and clean profiles.

**Comment by pmac** [comment]
Ah! Thanks for the followup. It was a misconfiguration in our cluster in Germany. This should now really be fixed.

**Comment by vasilicatamas** [comment]
Thanks @pmac! I confirm that the "Manage your Email Preferences" page is successfully loaded on both Stage [Train 1.203.54] and Prod [Train 1.203.4] .
