### ISSUE TITLE
CTMS: Distribute newsletter settings to newsletters

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/basket#685]
In CTMS, newsletter settings have defaults, as well as per-newsletter settings.

When adding a new subscription, the format (HTML or text) and language should be applied, and the source URL if provided at the time of subscription.

When updating the format choice or language, the change should be applied to existing subscriptions.

For example, going from HTML to Text would send something like this to CTMS:

```json
{
   "email": {
     "format": "T",
     "lang": "en"
   },
   "newsletters": [
     {
       "name": "app-dev",
       "subscribed": true,
       "format": "T",
       "lang": "en"
     }
   ]
}
```

and adding a new subscription with a source URL:

```json
{
   "newsletters": [
     {
       "name": "mozilla-foundation",
       "subscribed": true,
       "format": "T",
       "lang": "en",
       "source": "https://donate.mozilla.org/en-US/"
     }
   ]
}
```

Currently, only the default choice is changed, and source URLs are discarded.

**Comment by pmac** [comment]
I thought I heard in a meeting that the choice of HTML or Text was going away? If that's true perhaps we don't need to worry about that part at least.

/cc @LaurenNiolet

**Comment by LaurenNiolet** [comment]
Let me check with legal on this. None of our email programs, (moco or mofo) are currently sending to text only. Juice isn't worth the squeeze.

**Comment by jwhitlock** [comment]
It doesn't have a huge impact either way. The logic for email format will be similar to newsletter language and source URL, so it is an incremental effort to support it. On the other hand, dropping it from the database schema may require a round of meetings with MoFo / Cinchy, which I think I'd prefer to defer until post-launch. 🤷
