### ISSUE TITLE
Remove Salesforce / SFDC interface code

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/basket#719]
Remove the Salesforce interface code from Basket:

* Remove paths for ``settings.SFDC_ENABLED``, assume not enabled
* Remove calls to ``basket.news.backends.sfdc.sfdc``, retaining the ones to ``basket.news.backends.ctms.ctms``
* Remove SFDC-only code paths, such as donation payment updates, or raise an exception if called
* Convert ``fxa_delete`` to non-generic CTMS code

When there is no more code that calls it:
* Drop the SFDC backend
* Drop Salesforce settings
* Rename tasks with `sfdc` in title

Also tracked as https://jira.mozilla.com/browse/OSS-435

**Comment by robhudson** [comment]
This work has been completed.
