### ISSUE TITLE
Turn off or adjust contact-level locking

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/basket#722]
The function [basket.news.tasks.get_lock](https://github.com/mozmeao/basket/blob/ff6bcf7f02f6e0f870de393196750174a47fec62/basket/news/tasks.py#L121-L129), called from several tasks and utility functions, has this comment:

> Get a lock for a specific key (usually email address)
>
> Needs to be done with a timeout because SFDC needs some time to populate its indexes before the duplicate protection works and queries will return results. Releasing the lock right after the task was run still allowed dupes.
>
> Does nothing if you get the lock, and raises RetryTask if not.

CTMS, the new backend for 2021, updates indexes before returning to the user, so duplicate protection should be immediate. The lock could be changed in a few ways:

* Disable it entirely by setting ``TASK_LOCKING_ENABLE`` to false
* Lower the ``TASK_LOCK_TIMEOUT`` to release the lock faster
* Release the lock at the end of the task

**Comment by robhudson** [comment]
task locking was removed d3fb5b33ff0c2fc5c7e5a2a70205495f88c166d0
