### ISSUE TITLE
Remove Salesforce-related code from basket

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/basket#785]
I trust @pmac who says that Basket isn't talking to Salesforce any more. 

In the work for #782 we had to drop the `Salesforce-FuelSDK` dependency, but that was fine as it wasn't being used anyway.

There are, however, some uses of `simple-salesforce` still in the code, but these look inert (other than when used in tests) and all should be removed, along with other mentions of Salesforce 

#### Success critera
- [ ] All Salesforce-related code is identified - [this doc](https://docs.google.com/document/d/1nOi_nVieILjfmqdyv6MbhuWojVludR54fZxaV9mP9SQ/edit#heading=h.5fbx7du29izt) may help with discovery or regression checking 
- [ ] All Salesforce-related code is removed
- [ ] CI is still happy
- [ ] We've checked there are no flags/switches/settings that mean Dev can't be used to shakedown the removal of Salesforce integration code
- [ ] Dev/demo seems to work fine

**Comment by jwhitlock** [comment]
See #719 as well

**Comment by robhudson** [comment]
This work has been completed.
