### ISSUE TITLE
Delete a list of contacts from SFMC

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#80]
List to be provided separately to me by @jessilyndavis.

* Docs for [delete API call at SFMC](https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/DeleteByContactIDs.htm)

**Comment by jessilyndavis** [comment]
Details for this particular cleanup:

"ContactTypeId": 3,
"DeleteOperationType": "ContactAndAttributes"

**Comment by jessilyndavis** [comment]
Contactkey = Subscriberkey in the file I'll get to you :)

**Comment by pmac** [comment]
Jess and I have tested this and it does work as long as the DE has a primary key. Unfortunately not all of the ones we need to delete from do, so we're still working on what to do. I've filed #91 to do the work once we get a full list of DEs and fields for this. I'm closing this one in favor of that one since we've now determined that this will work.

**Comment by jessilyndavis** [comment]
@pmac - this is actually a slightly different flavor to the delete process. This one-time call is needed specifically to remove some dupes from our system with a "ContactTypeId": 3.  Can we reopen? And tackle by end of this month?

**Comment by pmac** [comment]
OH right. Sorry. Sure.

**Comment by pmac** [comment]
@jessilyndavis now that we've done some deletions using SSJS from SFMC itself, is this still needed?

**Comment by jessilyndavis** [comment]
I need to investigate if we can do this special deletion process using SSJS. (it's a different delete setup than the one we just did).

Do you prefer to leave this thread open? Or close it and reopen it if/when needed?

**Comment by pmac** [comment]
We can leave it open. And I'm happy to run it via the API still. Just checking :)

**Comment by jessilyndavis** [comment]
Hey @pmac - can we try this out on a sample contact this week together? 

The correct documentation is:
https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/DeleteByContactKeys.htm

I'm working on getting a few sample contacts to try deleting here:
https://docs.google.com/spreadsheets/d/1VjLx_g-5CeaHWnwdbyHaq2W2fv0MDyAthqHG5AdfUWs/edit#gid=1973791120

Let me know when the timing is good on your side to play with this - and I'll work on getting the contacts ready.

Thanks!

Jess

**Comment by pmac** [comment]
@jessilyndavis sure. throw something on my calendar.

**Comment by robhudson** [comment]
With Salesforce no longer used, I'm closing this.
