### ISSUE TITLE
Add management command to delete emails from SFMC Data Extensions

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#91]
This can not be done from the SFMC web app if said Data Extension is "non sendable".

¯\\\_(ツ)\_/¯

Such deletions can be done via the API (we've [successfully tested this](https://bugzilla.mozilla.org/show_bug.cgi?id=1466223)). So it'd be best if basket had a management command that would check a list of Data Extensions (to be provided by @jessilyndavis) for an email address (or list of addresses) and delete the row if found.

**Comment by pmac** [comment]
@jessilyndavis is this still needed after we've successfully tested the SSJS stuff within SFDC?

**Comment by jessilyndavis** [comment]
Nope! Let's close this. I'll close the bug too.

Thanks, Pmac!
