### ISSUE TITLE
Manage waitlists as a generic list

### ISSUE THREAD

**Issue by leplatrem** [mozmeao/basket#952]
Currently, the notion is waitlists is managed through [explicit contact fields](https://github.com/mozmeao/basket/blob/341facbb2b199bfe2f26488942d0fa251010c1c8/basket/news/backends/ctms.py#L84-L87).

Currently, Basket receives these fields in contact data from Bedrock:
```json
{
    "fpn_country": "fr",
    "fpn_platform": "win64",
}
```
And we transform them like this before posting to CTMS:
```json
{
    "vpn_waitlist": {
        "geo": "fr",
        "platform": "win64",
    }
}
```

We are now implementing a new way of managing waitlists in https://github.com/mozilla-it/ctms-api/pull/492, in order to make them generic and save ourselves redeploys when onboarding new ones.

In order to subscribe a contact to a new waitlist, we propose this:
```json
{
    "waitlists": [
        {
           "name": "vpn",
           "fields": {
               "geo": "fr", 
               "platform": "win64", 
            },
        },
    ]
```
And to unsubscribe:
```json
{
    "waitlists": [
        {
           "name": "vpn",
           "subscribed": false,
           ...
        },
    ]
```

I could navigate the basket source code, and more or less visualize the necessary changes in `backends/ctms.py` to support the new format. 
However, I'm a bit lost with other parts, like what values would have to be presented in a new `waitlists` multiple choice field in `SubscribeForm`, or the interactions with Bedrock forms. 

Could you please guide us so that we can prepare the Basket migration to our new structure?

Thanks a lot in advance for your insights

(Note: we will continue to support the legacy format for a while to smooth the transition)

**Comment by pmac** [comment]
Basket has no way of knowing if a request is for a waitlist or a newsletter subscription. They're nearly identical save that sometimes some extra data is sent, as you said above. I don't think that's always the case though.

**Comment by pmac** [comment]
We could change things in basket to have a new waitlists thing, or a boolean field for newsletters that indicate it's a waitlist. When do you plan on needing these changes in basket?

**Comment by leplatrem** [comment]
> Basket has no way of knowing if a request is for a waitlist or a newsletter subscription. 

From what I understood, everything happens in https://github.com/mozmeao/basket/blob/44ce26bbcd255456eabc4c3d6a9a740e2daff85e/basket/news/backends/ctms.py#L199

Where we would turn "flat fields" into "nested" CTMS data (eg. `{"newsletters": [....], "waitlists": [...]}`)

> They're nearly identical save that sometimes some extra data is sent, as you said above. 

I see. And IIUC, since waitlists are hardcoded in basket, we can pick the extra fields explicitly (eg. pick `fpn_country`, `fpn_platform`).

> We could change things in basket to have a new waitlists thing, or a boolean field for newsletters that indicate it's a waitlist. 

We would like to avoid having to redeploy basket and ctms when a new waitlist is created.

Having a boolean is not a bad idea indeed. 

We could also have a naming convention on newsletters, and build the list of waitlists in `ctms.py`. 

Something like this would support any arbitrary waitlists in the future:

```py
# pseudo-code

is_waitlist = newsletter["name"].endswith("-waitlist")
if is_waitlist:
     waitlist_name = newsletter["name"].replace("-waitlist", "")
     waitlist_fields = {}
     for field, value in newsletter.items():
          waitlist_slug = waitlist_name.replace("-", "_")
          if field.startswith(f"{waitlist_slug}_"):
               field_name = field.replace(f"{waitlist_name}_", "")
               waitlist_fields[field_name] = value

     waitlists.append({
        "name": waitlist_name,
        "fields": waitlist_fields
     })

```

For example:
```
name=super-product-waitlist
super_product_country=fr
super_product_currency=eur
```

Would be turned into:
```
{
  "name": "super-product",
  "fields": {
     "country": "fr",
     "currency": "eur",
   }
}
```

What do you think? 

(other details like unsubscribing would work like newsletters...)

> When do you plan on needing these changes in basket?

We decided to freeze onboarding of new waitlists until this is resolved. Otherwise each new waitlist adds up technical debt. If you are available to review pull requests in the next weeks, I'd be happy to implement the changes :)

**Comment by pmac** [comment]
I remain curious why we need to have custom fields for each waitlist. Could we have a few generic fields avaliable for any newsletter or waitlist? Or could we just use our existing fields like `country` instead of needing new ones like `fpn_country`?

**Comment by pmac** [comment]
> We could also have a naming convention on newsletters, and build the list of waitlists in ctms.py.

I think we already have a few waitlists that don't fit this convention and would take some coordination to change the name. This could work, but does seem potentially more fragile or error prone. I think a boolean field on basket's newsletters DB table would be the best bet, then we can manage them in the admin.

**Comment by pmac** [comment]
> We would like to avoid having to redeploy basket and ctms when a new waitlist is created.

I'm not sure how we can do this without anticipating which new fields to expect with each and what data types they'll be.

**Comment by pmac** [comment]
Also, will this work also mean we no longer need to deploy CTMS to add a new newsletter as well? That'd be great. We do that frequently as well.

**Comment by pmac** [comment]
> Yes, that is already done and deployed. The latest newsletter that we onboarded didn't require any redeploy. A SRE only has to run a command to map the newsletter slug with the Acoustic column.

Nice!

> I was thinking we could keep the hardcoded stuff for the existing waitlists that we have (vpn and relay). The convention would only apply for the new ones we onboard.

But basket still needs to know which ones are waitlists in order to use the new API. Basket doesn't have a separate API for waitlists since waitlists are exactly the same as newsletters, just a list of email addresses to which we'll send email someday. 

> I understand that for VPN it may not be the same country. 

For VPN it's the country in which they live and from which they'll be buying the service. The limitation is on where one can buy it, not where one can use it.

**Comment by leplatrem** [comment]
Implemented in https://github.com/mozmeao/basket/pull/962
