### ISSUE TITLE
Unwanted strings are displayed at the top of the "Manage your Email Preferences" page

### ISSUE THREAD

**Issue by mariaberlinger** [mozmeao/basket#982]
**FxA version:**
- 1.252.2;

**Prerequisites:**
- Have an fxa account;

**Steps to reproduce:**
1. Navigate to https://accounts.stage.mozaws.net/ and login using an existing account;
2. Click on the "Email communications" option displayed in the navigation menu;
3. Observe the page;

**Expected result:**
- The page is correctly displayed;

**Actual result:**
- At the top of the page unwanted strings are displayed;

**Notes:**
- See attached screenshot;
![image](https://user-images.githubusercontent.com/54393305/220929595-ecd619ab-a3ef-4687-90cd-56dc5c1087fc.png)

**Comment by alexgibson** [comment]
This should be fixed in https://github.com/mozilla/bedrock/pull/12790

**Comment by robhudson** [comment]
The bedrock bug of the same: https://github.com/mozilla/bedrock/issues/12789

**Comment by mariaberlinger** [comment]
This is verified as fixed in Train 1.252.2 production.  Unwanted strings are no longer displayed at the top of the page.
